name: my_map
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.0.2
  geolocator: ^11.0.0  
  permission_handler: ^11.3.0  
  geocoding: ^3.0.0
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  json_annotation: ^4.0.1

  # flutter_riverpod: any
  flutter_riverpod: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true
